# Request
sensor_msgs/Image img
float64[9] intrinsics
float64[5] distortion
sensor_msgs/Image depth_img
geometry_msgs/TransformStamped initial_pose
---
# Result
bool success
geometry_msgs/TransformStamped tracked_pose